project:
  type: website

website:
  title: "quarto_with_actions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  echo: false
  message: false
  warning: false

